# 日志服务器的地址
url: http://192.168.88.244:8082/log

# 数据库连接池配置
address: topview102
port: 3306
database: mc_streaming
user: root
password: 430525
connectionTimeout: 30000
#连接超时时间 默认值：30000（30秒）
minimumIdle: 10
#最小空闲连接数
maximumPoolSize: 50
#池允许达到的最大大小，包括空闲和正在使用的连接
